default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:

      - id: local-ruff-check
        name: ruff check
        entry: uv run ruff check src --force-exclude --fix --exit-non-zero-on-fix
        require_serial: true
        language: unsupported
        pass_filenames: false

      - id: local-ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude --exit-non-zero-on-format
        require_serial: true
        language: unsupported
        types: [ python ]

      - id: mypy
        name: mypy type checks
        entry: uv run mypy
        language: unsupported
        types: [ python ]
